# Generated by Django 2.0.3 on 2019-07-15 15:48

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please enter a posting title', max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Contents')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blog/post/%Y')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
